// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using WebApplication4.DB;

#nullable disable

namespace WebApplication4.Migrations
{
    [DbContext(typeof(Mydbcontext))]
    [Migration("20230329041309_sv1")]
    partial class sv1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication4.Models.Lop", b =>
                {
                    b.Property<string>("MaLop")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("MaLop");

                    b.ToTable("Lop");
                });

            modelBuilder.Entity("WebApplication4.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("NUMBER(1)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("TenSV")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("MaSV");

                    b.ToTable("SInhVien");
                });
#pragma warning restore 612, 618
        }
    }
}
