// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication6.Db;

#nullable disable

namespace WebApplication6.Migrations
{
    [DbContext(typeof(Mydbcontext))]
    partial class MydbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.15");

            modelBuilder.Entity("WebApplication6.Models.HocSinh", b =>
                {
                    b.Property<string>("MaHS")
                        .HasColumnType("TEXT");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LopMaLop")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenHS")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaHS");

                    b.HasIndex("LopMaLop");

                    b.ToTable("HocSinh");
                });

            modelBuilder.Entity("WebApplication6.Models.Lop", b =>
                {
                    b.Property<string>("MaLop")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaLop");

                    b.ToTable("Lop");
                });

            modelBuilder.Entity("WebApplication6.Models.HocSinh", b =>
                {
                    b.HasOne("WebApplication6.Models.Lop", null)
                        .WithMany("hocSinhs")
                        .HasForeignKey("LopMaLop");
                });

            modelBuilder.Entity("WebApplication6.Models.Lop", b =>
                {
                    b.Navigation("hocSinhs");
                });
#pragma warning restore 612, 618
        }
    }
}
