// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Db;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(MyDBContext))]
    [Migration("20230331015750_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.15");

            modelBuilder.Entity("WebApplication1.Models.DanhMuc", b =>
                {
                    b.Property<string>("MaDM")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenDM")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaDM");

                    b.ToTable("DanhMuc");
                });

            modelBuilder.Entity("WebApplication1.Models.SanPham", b =>
                {
                    b.Property<string>("MaSP")
                        .HasColumnType("TEXT");

                    b.Property<string>("DanhMucMaDM")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaDM")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaSP");

                    b.HasIndex("DanhMucMaDM");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("WebApplication1.Models.SanPham", b =>
                {
                    b.HasOne("WebApplication1.Models.DanhMuc", null)
                        .WithMany("sanPhams")
                        .HasForeignKey("DanhMucMaDM");
                });

            modelBuilder.Entity("WebApplication1.Models.DanhMuc", b =>
                {
                    b.Navigation("sanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
