// <auto-generated />
using System;
using Bai1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Bai1.Migrations
{
    [DbContext(typeof(ModelContext))]
    [Migration("20230427075255_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("EFCORE1")
                .UseCollation("USING_NLS_COMP")
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Bai1.Models.Category", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NAME");

                    b.Property<decimal?>("Status")
                        .HasColumnType("NUMBER")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.ToTable("CATEGORY", "EFCORE1");
                });

            modelBuilder.Entity("Bai1.Models.Product", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<decimal>("Id"), 1L, 1);

                    b.Property<decimal?>("Categoryid")
                        .HasColumnType("NUMBER")
                        .HasColumnName("CATEGORYID");

                    b.Property<DateTime?>("Createdate")
                        .HasColumnType("DATE")
                        .HasColumnName("CREATEDATE");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NAME");

                    b.Property<decimal?>("Price")
                        .HasColumnType("NUMBER")
                        .HasColumnName("PRICE");

                    b.Property<decimal?>("Status")
                        .HasColumnType("NUMBER")
                        .HasColumnName("STATUS");

                    b.HasKey("Id");

                    b.ToTable("PRODUCT", "EFCORE1");
                });
#pragma warning restore 612, 618
        }
    }
}
