// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using WebApplication5.Db;

#nullable disable

namespace WebApplication5.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230405082913_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication5.Models.Lop", b =>
                {
                    b.Property<string>("MaLop")
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("c_ma_lop");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("c_ten_lop");

                    b.HasKey("MaLop");

                    b.ToTable("Lop");
                });

            modelBuilder.Entity("WebApplication5.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<bool>("GioiTinh")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("LopMaLop1")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("TenSV")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("MaSV");

                    b.HasIndex("LopMaLop1");

                    b.HasIndex("MaLop");

                    b.ToTable("SinhVien");
                });

            modelBuilder.Entity("WebApplication5.Models.SinhVien", b =>
                {
                    b.HasOne("WebApplication5.Models.Lop", null)
                        .WithMany("SinhViens")
                        .HasForeignKey("LopMaLop1");

                    b.HasOne("WebApplication5.Models.Lop", "Lop")
                        .WithMany()
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lop");
                });

            modelBuilder.Entity("WebApplication5.Models.Lop", b =>
                {
                    b.Navigation("SinhViens");
                });
#pragma warning restore 612, 618
        }
    }
}
